-- Seed: bottle_opening_reasons and bottle_discard_reasons
-- Unsafe: do not re-run (no ON CONFLICT guard — IDs are generated by the DB)

INSERT INTO bottle_opening_reasons (name, is_default) VALUES
  ('Outro',                                    TRUE),
  ('Vacinação em campanha ou mutirão',          FALSE),
  ('Demanda inesperada',                        FALSE),
  ('Frasco anterior perdido ou vencido',        FALSE),
  ('Substituição de frasco contaminado',        FALSE);

INSERT INTO bottle_discard_reasons (name, is_default) VALUES
  ('Dose remanescente após término da sessão',  TRUE),
  ('Frasco vencido',                            FALSE),
  ('Quebra ou dano ao frasco',                  FALSE),
  ('Falha na cadeia de frio',                   FALSE),
  ('Contaminação',                              FALSE);
