-- Seed: locations (zona urbana de Cáceres/MT) + uma vaccine_room por location
-- Fonte: Guia do Usuário SUS — Secretaria Municipal de Saúde de Cáceres/MT (pág. 4)
-- Unsafe: do not re-run (no ON CONFLICT guard — IDs are generated by the DB)

WITH inserted_locations AS ( 
  INSERT INTO locations (name, address, type) VALUES
    ('Centro Referencial de Saúde',        'Avenida Presidente Castelo Branco, s/nº - São Miguel, Cáceres - MT',          'ubs'),
    ('UBS Dr. Ademar R. de Oliveira',      'Rua São Pedro, 1211 - Cavalhada II, Cáceres - MT',                            'ubs'),
    ('UBS Vila Irene',                     'Rua São Pedro, 1211 - Cavalhada II, Cáceres - MT',                            'ubs'),
    ('UBS Santa Isabel',                   'Rua Rouxinol, s/nº - Santa Isabel, Cáceres - MT',                             'ubs'),
    ('UBS Marajoara',                      'Rua Rouxinol, s/nº - Santa Isabel, Cáceres - MT',                             'ubs'),
    ('UBS CAIC',                           'Rua Hermes da Fonseca, s/nº - Jardim Cidade Nova, Cáceres - MT',              'ubs'),
    ('UBS Cohab Nova',                     'Rua dos Marinhos, s/nº - Cohab Nova, Cáceres - MT',                           'ubs'),
    ('UBS Jardim Guanabara',               'Rua Cerejeiras, s/nº - Jardim Guanabara, Cáceres - MT',                       'ubs'),
    ('UBS Jardim Paraíso',                 'Rua 31 de Março, s/nº - Jardim Paraíso, Cáceres - MT',                        'ubs'),
    ('UBS Rodeio',                         'Rua Madri, s/nº - Rodeio, Cáceres - MT',                                      'ubs'),
    ('UBS Vista Alegre',                   'Rua das Margaridas, 557 - Vista Alegre, Cáceres - MT',                        'ubs'),
    ('UBS Vila Real',                      'Rua Bélgica, 11 - Vila Real, Cáceres - MT',                                   'ubs'),
    ('UBS Vitória Régia',                  'Rua Amazonas, s/nº - Jardim Popular, Cáceres - MT',                           'ubs'),
    ('UBS Jardim das Oliveiras',           'Rua dos Jequitis, s/nº - Jardim das Oliveiras, Cáceres - MT',                 'ubs'),
    ('UBS Santos Dumont',                  'Rua da Biologia, s/nº - Residencial Universitário, Cáceres - MT',             'ubs'),
    ('Unidade Móvel de Saúde',             'Avenida Getúlio Vargas, 896 - Jardim Celeste, Cáceres - MT',                  'lugar_temporario')
  RETURNING id
)
INSERT INTO vaccine_rooms (location_id, description)
SELECT id, 'Sala'
FROM inserted_locations;
